extends Node
## Sound effects. Autoloaded as `Sfx`.
##
## The clips are generated by tools/make_sfx.py, which is also where the reason
## each one sounds the way it does is written down. This side owns three things
## the files cannot: when a sound is allowed to repeat, how much it moves when
## it does, and whether the player wants any of it at all.
##
##   Sfx.play("fill")
##
## There is deliberately no click on every button. Nearly every button in the
## game already causes a sound — it changes screen, turns a card, undoes a
## stroke — so a generic press would double most of them, and the two buttons
## pressed most often (Fill and Mark) only switch a mode that the button's own
## highlight already reports. Ticking under all of that is the whole difference
## between a quiet game and a busy one.

## Everything the game can make a noise about.
##
## `clips` is a list because the two sounds a player hears hundreds of times an
## hour ship as detuned variants; the rest have one. `pitch` is the random
## spread applied per play, and `gap` is the shortest interval at which the same
## sound will sound twice.
##
## The pitch figures are small on purpose. Six percent is enough that a dragged
## row of fills reads as a hand moving rather than a loop point, and little
## enough that it never sounds like a tune. The two tonal sounds — the line
## confirmation and the solve chord — get two percent, because they have real
## pitch to detune and a wobbling chord sounds broken rather than alive.
const BANK := {
	"fill": {
		"clips": [
			preload("res://assets/sfx/fill_a.wav"),
			preload("res://assets/sfx/fill_b.wav"),
			preload("res://assets/sfx/fill_c.wav"),
		],
		"pitch": 0.06, "gap": 28,
	},
	"mark": {
		"clips": [
			preload("res://assets/sfx/mark_a.wav"),
			preload("res://assets/sfx/mark_b.wav"),
		],
		"pitch": 0.06, "gap": 28,
	},
	"line": {"clips": [preload("res://assets/sfx/line.wav")], "pitch": 0.02, "gap": 90},
	"undo": {"clips": [preload("res://assets/sfx/undo.wav")], "pitch": 0.05, "gap": 40},
	"reset": {"clips": [preload("res://assets/sfx/reset.wav")], "pitch": 0.04, "gap": 120},
	"solved": {"clips": [preload("res://assets/sfx/solved.wav")], "pitch": 0.02, "gap": 400},
	"stamp": {"clips": [preload("res://assets/sfx/stamp.wav")], "pitch": 0.03, "gap": 400},
	"flip": {"clips": [preload("res://assets/sfx/flip.wav")], "pitch": 0.05, "gap": 120},
	"nav": {"clips": [preload("res://assets/sfx/nav.wav")], "pitch": 0.05, "gap": 60},
	"locked": {"clips": [preload("res://assets/sfx/locked.wav")], "pitch": 0.04, "gap": 200},
}

## Enough voices that a fast drag across a row never cuts its own tail off.
## One player per sound would: a 55 ms tap fired every 28 ms overlaps itself
## twice over, and restarting a stream mid-tap is the click you hear in games
## that do this with a single AudioStreamPlayer.
const VOICES := 8

var _pool: Array[AudioStreamPlayer] = []
var _next: int = 0
var _last_at: Dictionary = {}      ## sound name -> Time.get_ticks_msec()
var _last_clip: Dictionary = {}    ## sound name -> index of the variant used


func _ready() -> void:
	for i in VOICES:
		var player := AudioStreamPlayer.new()
		# The files carry the mix — see the peak column in make_sfx.py — so the
		# engine plays them flat. Anything set here would be a second, invisible
		# balance to keep in step with the first.
		player.volume_db = 0.0
		add_child(player)
		_pool.append(player)


## The single entry point. Unknown names warn rather than fail: a missing sound
## is a wiring mistake, not a reason to take a screen down with it.
func play(name: String) -> void:
	# Name checked before the setting, so a typo still reports itself to whoever
	# is testing with the sound turned off.
	if not BANK.has(name):
		push_warning("No sound named '%s'" % name)
		return
	if not enabled():
		return
	var entry: Dictionary = BANK[name]

	# Painting a 15x15 board with the mouse down delivers a cell every few
	# milliseconds on a fast drag. Every one of those is a real event and every
	# one of them wants a tap, but past about thirty a second they stop being
	# taps and become a buzz, so the extra ones are dropped rather than queued.
	var now: int = Time.get_ticks_msec()
	if now - int(_last_at.get(name, -100000)) < int(entry["gap"]):
		return
	_last_at[name] = now

	var player: AudioStreamPlayer = _pool[_next]
	_next = (_next + 1) % _pool.size()
	player.stream = _variant(name, entry["clips"])
	player.pitch_scale = 1.0 + randf_range(-1.0, 1.0) * float(entry["pitch"])
	player.play()


## Read from the save on every play rather than cached at startup. The settings
## toggle writes the key and rebuilds the screen — there is no signal to listen
## to and nowhere to push the change from — and a dictionary lookup per tap is
## far cheaper than a stale flag.
func enabled() -> bool:
	return bool(SaveGame.setting("sound", true))


## Never the same variant twice running. Pure randomness clusters, and a
## cluster is exactly the mechanical repeat the variants exist to avoid.
func _variant(name: String, clips: Array) -> AudioStream:
	if clips.size() == 1:
		return clips[0]
	var last: int = int(_last_clip.get(name, -1))
	var index: int = randi() % clips.size()
	if index == last:
		index = (index + 1) % clips.size()
	_last_clip[name] = index
	return clips[index]
